import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import './App.css';

const trains = [
  { id: 1, name: 'Sonar Bangla Express', no: '788', from: 'Dhaka', to: 'Chattogram', depart: '07:30', arrive: '12:10', duration: '4h 40m', fare: 1040, seats: 46 },
  { id: 2, name: 'Mahanagar Provati', no: '704', from: 'Dhaka', to: 'Chattogram', depart: '09:15', arrive: '14:35', duration: '5h 20m', fare: 890, seats: 23 },
  { id: 3, name: 'Parabat Express', no: '710', from: 'Dhaka', to: 'Sylhet', depart: '06:20', arrive: '12:55', duration: '6h 35m', fare: 760, seats: 31 }
];

const trip = { pnr: 'RF7A9K2', train: trains[0], date: '04 Sep 2026', coach: 'C', seat: '24', passenger: 'Amina Rahman', status: 'Confirmed' };
function App(){ return <Routes><Route path="/login" element={<Login/>}/><Route path="*" element={<Shell/>}/></Routes> }
function Login(){ const go=useNavigate(); return <main className="login"><section className="login-card"><div className="brand"><b>R</b> RailFlow</div><h1>Welcome back</h1><p>Sign in to manage your railway journeys.</p><label>Email address<input defaultValue="amina@example.com" type="email"/></label><label>Password<input type="password" defaultValue="railflow"/></label><button className="primary wide" onClick={()=>go('/')}>Sign in</button><div className="or">or continue with</div><button className="secondary wide">Google account</button><small>New to RailFlow? <a href="#register">Create an account</a></small></section><aside className="login-art"><span>🚆</span><h2>Every journey, in one place.</h2><p>Search trains, select seats, pay securely, and keep tickets on hand.</p></aside></main> }
function Shell(){ return <div className="app"><aside className="sidebar"><Link className="brand" to="/"><b>R</b> RailFlow</Link><nav><NavLink end to="/">▦ Dashboard</NavLink><NavLink to="/search">⌕ Find trains</NavLink><NavLink to="/booking">＋ Book a ticket</NavLink><NavLink to="/tickets">▣ My tickets</NavLink><NavLink to="/cancellation">↩ Cancellation</NavLink><NavLink to="/profile">◉ Personal info</NavLink><NavLink to="/settings">⚙ Settings</NavLink></nav><NavLink className="logout" to="/login">⇥ Log out</NavLink></aside><section className="content"><header><div><span className="eyebrow">Tuesday, 19 August 2026</span><h1>Railway ticket management</h1></div><Link className="avatar" to="/profile">AR</Link></header><Routes><Route path="/" element={<Dashboard/>}/><Route path="/search" element={<Search/>}/><Route path="/booking" element={<Booking/>}/><Route path="/payment" element={<Payment/>}/><Route path="/tickets" element={<Tickets/>}/><Route path="/cancellation" element={<Cancellation/>}/><Route path="/profile" element={<Profile/>}/><Route path="/settings" element={<Settings/>}/></Routes></section></div> }
function Dashboard(){ return <><section className="hero"><div><span className="eyebrow pink">GOOD MORNING</span><h2>Hi Amina!</h2><p>Your next journey is only 16 days away.</p><Link className="primary" to="/tickets">View ticket</Link></div><div className="hero-train">🚆</div></section><h3>Travel snapshot</h3><div className="metrics"><Metric n="08" label="Total trips"/><Metric n="02" label="Upcoming journeys" coral/><Metric n="01" label="Refund request"/></div><div className="grid two"><Panel title="Upcoming journey"><TicketCompact/><Link to="/tickets">View all tickets →</Link></Panel><Panel title="Recent activity"><ul className="activity"><li><b>Ticket confirmed</b><span>Sonar Bangla Express · Today</span></li><li><b>Payment completed</b><span>BDT 1,040 · 16 Aug 2026</span></li><li><b>Journey completed</b><span>Dhaka to Rajshahi · 12 Aug 2026</span></li></ul></Panel></div></> }
function Metric({n,label,coral}) { return <article className={'metric '+(coral?'coral':'')}><strong>{n}</strong><span>{label}</span></article> }
function Panel({title,children}){return <section className="panel"><div className="panel-title"><h3>{title}</h3><span>•••</span></div>{children}</section>}
function TicketCompact(){return <div className="ticket-compact"><div><b>DHA</b><small>Dhaka</small></div><div className="route-line"><span>07:30</span><i></i><span>4h 40m</span></div><div><b>CTG</b><small>Chattogram</small></div><footer><span>04 Sep · Coach C · Seat 24</span><b>Confirmed</b></footer></div>}
function Search(){ const [query,setQuery]=useState({from:'Dhaka',to:'Chattogram',date:'04 Sep 2026'}); return <Page title="Find a train" sub="Search live availability and fares for your journey."><form className="search-form" onSubmit={e=>e.preventDefault()}><Field label="From" value={query.from}/><Field label="To" value={query.to}/><Field label="Departure" value={query.date}/><button className="primary">Search trains</button></form><h3>Available trains</h3>{trains.filter(t=>t.from===query.from&&t.to===query.to).map(t=><TrainRow key={t.id} t={t}/>)}</Page> }
function Field({label,value}){return <label className="field">{label}<input defaultValue={value}/></label>}
function TrainRow({t}){return <article className="train-row"><div><b>{t.name}</b><small>Train {t.no} · Intercity</small></div><div><b>{t.depart}</b><small>{t.from}</small></div><div className="travel"><span>{t.duration}</span><i></i><small>Direct</small></div><div><b>{t.arrive}</b><small>{t.to}</small></div><div><b>BDT {t.fare}</b><small>{t.seats} seats left</small></div><Link className="primary" to={'/booking?train='+t.id}>Select</Link></article>}
function Booking(){ const go=useNavigate(); const [seat,setSeat]=useState('C-24'); return <Page title="Book your ticket" sub="Sonar Bangla Express · Dhaka to Chattogram · 04 Sep 2026"><div className="grid booking-layout"><Panel title="1. Select seat"><div className="seat-key"><span className="available"></span> Available <span className="chosen"></span> Selected <span className="occupied"></span> Occupied</div><div className="seat-map">{Array.from({length:36},(_,i)=>{let s='C-'+(i+1);let unavailable=[3,4,9,16,20,21,29].includes(i+1); return <button key={s} disabled={unavailable} className={seat===s?'selected':''} onClick={()=>setSeat(s)}>{i+1}</button>})}</div></Panel><aside className="summary"><h3>Journey summary</h3><b>Dhaka <span>→</span> Chattogram</b><p>Sonar Bangla Express · 07:30</p><hr/><div><span>Passenger</span><b>Amina Rahman</b></div><div><span>Seat</span><b>{seat}</b></div><div><span>Base fare</span><b>BDT 980</b></div><div><span>Service charge</span><b>BDT 60</b></div><div className="total"><span>Total</span><b>BDT 1,040</b></div><button className="primary wide" onClick={()=>go('/payment')}>Continue to payment</button></aside></div></Page> }
function Payment(){ const go=useNavigate(); const [method,setMethod]=useState('card'); const [mobileProvider,setMobileProvider]=useState('bKash'); const providers=[['bKash','bKash','bkash'],['Nagad','Nagad','nagad'],['Rocket','Rocket','rocket'],['Upay','Upay','upay']]; return <Page title="Secure payment" sub="Complete payment to confirm your seat."><div className="grid pay-layout"><Panel title="Payment method"><div className="payment-options">{[['card','Credit or debit card'],['mobile','Mobile banking'],['bank','Bank transfer']].map(([id,label])=><label className={method===id?'pay-choice active':'pay-choice'} key={id}><input type="radio" checked={method===id} onChange={()=>setMethod(id)}/><span>{id==='card'?'▣':id==='mobile'?'◈':'▤'}</span>{label}</label>)}</div>{method==='card'&&<div className="card-form"><Field label="Cardholder name" value="Amina Rahman"/><Field label="Card number" value="4242 4242 4242 4242"/><div className="form-two"><Field label="Expiry date" value="09 / 29"/><Field label="CVV" value="•••"/></div></div>}{method==='mobile'&&<div className="mobile-form"><p>Choose your mobile banking provider</p><div className="provider-grid">{providers.map(([id,label,style])=><button type="button" key={id} className={'provider '+style+(mobileProvider===id?' selected':'')} onClick={()=>setMobileProvider(id)}><strong>{label}</strong><small>{mobileProvider===id?'Selected':'Pay with '+label}</small></button>)}</div><Field label={mobileProvider+' account number'} value="01712 345 678"/><small className="payment-hint">You will confirm the payment securely in {mobileProvider}.</small></div>}</Panel><aside className="summary"><h3>Order total</h3><div><span>Ticket fare</span><b>BDT 980</b></div><div><span>Service charge</span><b>BDT 60</b></div><div className="total"><span>Amount due</span><b>BDT 1,040</b></div><button className="primary wide" onClick={()=>go('/tickets')}>{method==='mobile'?'Pay with '+mobileProvider:'Pay BDT 1,040'}</button><small className="secure">🔒 Payments are encrypted and secure.</small></aside></div></Page>}
function Tickets(){return <Page title="My tickets" sub="Your active, completed, and cancelled railway journeys."><div className="tabs"><button className="active">Upcoming (2)</button><button>Past journeys</button><button>Cancelled</button></div><div className="ticket-list"><TicketCard/><TicketCard second/></div></Page>}
function TicketCard({second}){return <article className="ticket-card"><div className="ticket-top"><b>{second?'PARABAT EXPRESS':'SONAR BANGLA EXPRESS'}</b><span>CONFIRMED</span></div><div className="ticket-route"><div><b>DHA</b><small>Dhaka · {second?'06:20':'07:30'}</small></div><div><i></i><small>{second?'6h 35m':'4h 40m'}</small></div><div><b>{second?'SYL':'CTG'}</b><small>{second?'Sylhet · 12:55':'Chattogram · 12:10'}</small></div></div><footer><span>{second?'10 Sep 2026 · Coach A · Seat 11':'04 Sep 2026 · Coach C · Seat 24'}</span><Link to="/cancellation">Manage ticket →</Link></footer></article>}
function Cancellation(){const [done,setDone]=useState(false); return <Page title="Cancel a ticket" sub="Review your refund before cancelling a confirmed ticket.">{done?<section className="success"><div>✓</div><h2>Cancellation submitted</h2><p>Your ticket has been cancelled. A refund of BDT 890 will be returned to your original payment method within 5–7 working days.</p><Link className="primary" to="/tickets">Back to tickets</Link></section>:<div className="grid cancel-layout"><Panel title="Ticket to cancel"><TicketCompact/><div className="notice">Cancellation policy: BDT 150 will be retained as a cancellation fee.</div></Panel><aside className="summary"><h3>Refund estimate</h3><div><span>Amount paid</span><b>BDT 1,040</b></div><div><span>Cancellation fee</span><b className="danger">− BDT 150</b></div><div className="total"><span>Refund amount</span><b>BDT 890</b></div><button className="danger-button wide" onClick={()=>setDone(true)}>Cancel ticket</button></aside></div>}</Page>}
function Profile(){return <Page title="Personal information" sub="Your passenger details are saved securely for faster booking."><div className="grid profile-layout"><Panel title="Profile details"><div className="profile-photo">AR</div><div className="form-two"><Field label="First name" value="Amina"/><Field label="Last name" value="Rahman"/></div><Field label="Email address" value="amina@example.com"/><Field label="Mobile number" value="+880 1712 345 678"/><button className="primary">Save changes</button></Panel><Panel title="Passenger documents"><div className="document"><div>▣</div><div><b>National ID</b><small>•••• 8765 · Verified</small></div><span>✓</span></div><button className="secondary">Manage documents</button></Panel></div></Page>}
function Settings(){return <Page title="Settings" sub="Control your app preferences and notifications."><div className="setting-list">{[['Journey alerts','Platform changes, delays, and cancellation updates'],['Promotional offers','Receive special fares and service updates'],['Two-factor authentication','Protect your RailFlow account']].map(([a,b],i)=><article className="setting" key={a}><div><b>{a}</b><small>{b}</small></div><label className="toggle"><input type="checkbox" defaultChecked={i!==1}/><i></i></label></article>)}</div></Page>}
function Page({title,sub,children}) {return <main className="page"><h2>{title}</h2><p className="sub">{sub}</p>{children}</main>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
